
# seed
seed: 1

# device
device: 'cuda:1'

# model
hidden_dim: 512
latent_dim: 2

# distribution
prior_distribution: ""

# train
num_epochs: 10
batch_size: 64
learning_rate: 0.001

# log
print_every: 100
fig_root: 'figs'