# environment
base_env: 'cheetah_vel' # ['cheetah_dir', 'cheetah_vel', 'ant_dir', 'ML1-pick-place-v2']

# project name
project_name: 'prompt-dt'

# dataset
train_dataset_mode: 'expert'
test_dataset_mode: 'expert'  # useful for test time finetune only
train_prompt_mode: 'expert'
test_prompt_mode: 'expert'
reward_mode: 'normal' # ['normal', 'delayed']
average_state_mean: true # compute state mean/std from all train+test data instead of a specific environment
pct_traj: 1.0

# transformer
embed_dim: 128
n_layer: 3
n_head: 1
activation_function: 'relu'
dropout: 0.1
K: 20  # input segment length
# the following options are only for input trajectories, not for trajectory prompts
no_r: false # deduct reward from rtg or not
no_rtg: false # input includes rtg or not

# prompt
no_prompt: true
prompt_method: "traj_prompt" #["traj_prompt", "goal_prompt"]
traj_prompt:
  prompt_episode: 1
  prompt_length: 5 #2
  # if true randomly select prompt trajectory
  # otherwise prefer prompt trajectory with higher return
  stochastic_prompt: true 

# training
per_env_batch_size: 16 # number of trajectory segments per batch in each training environment
learning_rate: 1.0e-4
weight_decay: 1.0e-4
warmup_steps: 10000  # 10000 * number of environments
max_iters: 5000
num_steps_per_iter: 10
# test in training environments every n iterations
train_eval_interval: 500 
# test in test environments every n iterations
test_eval_interval: 500 #100
save_interval: 500
# for both train and evaluation
# eval n episodes for each environment
num_eval_episodes: 20 #50
# normalize state or not
# for both train and evaluation
# for both train trajectory and prompt trajectory 
no_state_normalize: false 

# evaluation
load_path: "cheetah_dir-2-env-expert-no_prompt-s1-20230314-220409" # where to load the model
checkpoint_name: "iter-0.pth"

# seed
seed: 1

# device
device: 'cuda:1'

# log
log_to_wandb: true
